openapi: 3.0.0
info:
  title: User Management API
  description: API for managing users with pagination support
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get users with pagination
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 1
            minimum: 1
        - name: size
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: List of users retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: "Alice"
                  email:
                    type: string
                    format: email
                    example: "alice@example.com"
        '400':
          description: Bad request - invalid parameter types
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Bad types for provided query parameters"